apiVersion: v1
data:
  config.yaml: |
    redis:
      expire_time: 100
      host: redis
      port: 6379
      db: 0
      password: ""

    server:
      port: 8080
      api_key: khkhkhkhk
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: teleport
