apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ccproj
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: master
        image: redis:7-alpine
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: redis-data
          mountPath: /data
        ports:
        - containerPort: 6379
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc