apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
  namespace: ccproj
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/sina/redis-data